<?php
require_once __DIR__.'/sendEmailClass.php';

$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$conn = new PDO($dsn);

$now = new DateTime();
$todayStr = $now->format('Y-m-d');
$weekday = (int)$now->format('N'); // 1 = Monday, 7 = Sunday

$isMonday = isset($_GET['isMonday']) ? $_GET['isMonday'] === 'Y' : false;
$period = isset($_GET['theperiod']) ? (int)$_GET['theperiod'] : 0;

// Holiday check
$holidayFile = __DIR__ . '/holiday.txt';
$holidayDates = file_exists($holidayFile) ? file($holidayFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) : [];
if (in_array($todayStr, $holidayDates)) exit;

// Check semester
$semester = $conn->query("SELECT SemesterID, StartDate, EndDate FROM tblbhssemester WHERE CurrentSemester = 'Y'")->fetch(PDO::FETCH_ASSOC);
if (!$semester) exit;

$start = new DateTime($semester['StartDate']);
$end = (new DateTime($semester['EndDate']))->modify('+1 day');
if ($now < $start || $now > $end) exit;

// Check if we should proceed based on weekday and isMonday flag
// Normal runs: Mon-Fri. Friday schedule can be forced on Saturday with isMonday=Y.
if (!(($weekday >= 2 && $weekday <= 5 && !$isMonday) || ($weekday === 1 && $isMonday))) exit;

echo 'test';
return;

// Determine block and day index based on rptstudentschedule96.cfm
$scheduleWeekday = $isMonday ? 1 : $weekday; // 1=Mon ... 5=Fri
$blockMap = [
    1 => [1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5], // Mon: A,B,C,D,E
    2 => [1 => 3, 2 => 1, 3 => 2, 4 => 4, 5 => 5], // Tue: C,A,B,D,E
    3 => [1 => 2, 2 => 3, 3 => 1, 4 => 4, 5 => 5], // Wed: B,C,A,D,E
    4 => [1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5], // Thu: A,B,C,D,E
    5 => [1 => 3, 2 => 1, 3 => 2, 4 => 4, 5 => 5], // Fri: C,A,B,D,E
];
$dayIndexMap = [
    1 => 5, // Mon is Day 5
    2 => 2, // Tue is Day 2
    3 => 3, // Wed is Day 3
    4 => 4, // Thu is Day 4
    5 => 1, // Fri is Day 1
];
if (!isset($blockMap[$scheduleWeekday][$period])) exit;
if (!isset($dayIndexMap[$scheduleWeekday])) exit;
$block = $blockMap[$scheduleWeekday][$period];
$dayIndex = $dayIndexMap[$scheduleWeekday];
// Load 1038 recipients
$email1038 = '';
$get1038 = $conn->query("SELECT Email3 FROM tblStaff WHERE GroupTeam LIKE '%1038%' AND CurrentStaff = 'Y'");
$emails = $get1038->fetchAll(PDO::FETCH_COLUMN);
if ($emails) $email1038 = implode(';', array_filter($emails));

// Fetch subjects needing attendance


$sql = "
SELECT
    s.SubjectName,
    s.SubjectID,
    t.FirstName,
    t.LastName,
    t.Email3,

    (SELECT TOP 1 r.RDate
     FROM tblbhsAttendanceRpt r
     WHERE r.SubjectID = s.SubjectID
       AND CONVERT(date, r.SDate) = '{today}'
     ORDER BY r.RDate DESC) AS rdate,

    (SELECT TOP 1 r2.RDate
     FROM tblbhsAttendanceRpt r2
     INNER JOIN tblBHSSubject s2 ON r2.SubjectID = s2.SubjectID
     WHERE s2.SameGroup = s.SameGroup
       AND CONVERT(date, r2.SDate) = '{today}'
     ORDER BY r2.RDate DESC) AS rdate2

FROM tblBHSSUBJECT s
JOIN tblStaff t ON s.TeacherID = t.StaffID
WHERE s.SemesterID = '{semester}'
  AND s.Block = '{block}'
  AND s.SDay LIKE '%{dayIndex}%'
  AND s.SubjectName NOT LIKE 'YYY%'
  AND s.Type <> 'C'
  AND s.SPA <> 0
ORDER BY
    t.FirstName,
    t.LastName,
    rdate DESC,
    s.SubjectName;
";

$sql = str_replace(
    ['{today}', '{semester}', '{block}', '{dayIndex}'],
    [
        addslashes($todayStr),
        addslashes($semester['SemesterID']),
        addslashes($block),
        addslashes($dayIndex)
    ],
    $sql
);


$stmt = $conn->query($sql);
$subjects = $stmt->fetchAll(PDO::FETCH_ASSOC);

foreach ($subjects as $subj) {
    if (empty($subj['rdate']) && empty($subj['rdate2']) && !empty($subj['Email3'])) {
        $toList = [
            ['email' => $subj['Email3'], 'name' => $subj['FirstName'] . ' ' . $subj['LastName']]
        ];

        // $ccList = [['email'=>'chanho.lee@bodwell.edu','name'=>'chano lee']];
        $ccList = [];
        $bccList = [];
        $additional = $email1038;
        if ($additional) {
            foreach (explode(';', $additional) as $addr) {
                if (!empty(trim($addr))) {
                    $bccList[] = ['email' => trim($addr), 'name' => ''];
                }
            }
        }
        $subject = "Attendance reminder on $todayStr";
        $html = "Dear {$subj['FirstName']},<br><br>" .
                "According to our records, we did not receive an attendance report for <b>{$subj['SubjectName']}</b> today. " .
                "Please submit the attendance report accordingly.<br><br><br>This message is automatically generated by Bodwell database system.";
        // sendEmail(
        //     ['email' => 'no-reply@bodwell.edu', 'name' => 'Attendance Reminder'],
        //     $toList, $ccList, $subject, $html, $bccList
        // );
    }
}
?>
