<!--- Attendance reminder - scheduled to send out at 9:39, 11:00, 12:21, 14:19 & 15:40 from Monday to Thursday and 10:35, 11:42, 12:49, 14:33 & 15:40 on every Friday --->
<!--- Holiday --->
<cfif now() gt parsedatetime("2022-01-10")>
<cfset file1 = "e:\admin.bodwell.edu\bhs\schedule\holiday.txt"><cfset hasholiday = "">
<cfif fileexists(file1)>
<cfloop index="line" file="#file1#">
<cfif dateformat(now(), "yyyy-mm-dd") is line><cfset hasholiday = line></cfif>
</cfloop>
</cfif>
<cfif hasholiday is "">
<!--- Only within current term --->
<cfquery name="getsemester" datasource="#session.dsname#" username="#session.dsnusername#" password="#session.dsnpassword#">
select semesterid, startdate, enddate from tblbhssemester where currentsemester = 'Y'
</cfquery>
<cfif now() gte getsemester.startdate and now() lte dateadd("d", 1, getsemester.enddate)>
<!--- Only Monday to Thursday with N for isFriday or Friday with Y for isFriday --->
<cfif (dayofweek(now()) gte 2 and dayofweek(now()) lte 5 and url.isFriday is "N") or (dayofweek(now()) is 6 and url.isFriday is "Y")>
<!--- Monday --->
<cfif dayofweek(now()) is 2>
<cfif url.theperiod is 1><cfset theblock = 1>
<cfelseif url.theperiod is 2><cfset theblock = 2>
<cfelseif url.theperiod is 3><cfset theblock = 3>
<cfelseif url.theperiod is 4><cfset theblock = 4>
<cfelseif url.theperiod is 5><cfset theblock = 5>
</cfif>
<!--- Tuesday --->
<cfelseif dayofweek(now()) is 3>
<cfif url.theperiod is 1><cfset theblock = 5>
<cfelseif url.theperiod is 2><cfset theblock = 1>
<cfelseif url.theperiod is 3><cfset theblock = 2>
<cfelseif url.theperiod is 4><cfset theblock = 3>
<cfelseif url.theperiod is 5><cfset theblock = 4>
</cfif>
<!--- Wednesday --->
<cfelseif dayofweek(now()) is 4>
<cfif url.theperiod is 1><cfset theblock = 4>
<cfelseif url.theperiod is 2><cfset theblock = 5>
<cfelseif url.theperiod is 3><cfset theblock = 1>
<cfelseif url.theperiod is 4><cfset theblock = 2>
<cfelseif url.theperiod is 5><cfset theblock = 3>
</cfif>
<!--- Thursday --->
<cfelseif dayofweek(now()) is 5>
<cfif url.theperiod is 1><cfset theblock = 3>
<cfelseif url.theperiod is 2><cfset theblock = 4>
<cfelseif url.theperiod is 3><cfset theblock = 5>
<cfelseif url.theperiod is 4><cfset theblock = 1>
<cfelseif url.theperiod is 5><cfset theblock = 2>
</cfif>
<!--- Friday --->
<cfelseif dayofweek(now()) is 6>
<cfif url.theperiod is 1><cfset theblock = 2>
<cfelseif url.theperiod is 2><cfset theblock = 3>
<cfelseif url.theperiod is 3><cfset theblock = 4>
<cfelseif url.theperiod is 4><cfset theblock = 5>
<cfelseif url.theperiod is 5><cfset theblock = 1>
</cfif>
</cfif>
<cfinclude template="../inc_email.cfm">
<cfquery name="getblock" datasource="#session.dsname#" username="#session.dsnusername#" password="#session.dsnpassword#">
select a.subjectname, a.subjectid, b.firstname, b.lastname, b.email3,
(select top 1 tblbhsattendancerpt.rdate from tblbhsattendancerpt where tblbhsattendancerpt.subjectid = a.subjectid and tblbhsattendancerpt.sdate = #parsedatetime(dateformat(now(), "yyyy-mm-dd"))#) as rdate,
(select top 1 C.rdate from tblbhsattendancerpt AS C INNER JOIN tblBHSSubject AS D ON C.SubjectID = D.SubjectID where D.samegroup = a.samegroup and C.sdate = #parsedatetime(dateformat(now(), "yyyy-mm-dd"))#) as rdate2
from tblbhssubject as a, tblstaff as b
where a.teacherid = b.staffid and a.semesterid = #getsemester.semesterid# and a.block = #theblock# and a.sday like '%#evaluate(dayofweek(now()) - 1)#%' and not a.subjectname like 'YYY%' and
a.type <> 'C' and a.spa <> 0 order by b.firstname, b.lastname, rdate desc, a.subjectname
</cfquery>
<cfoutput query="getblock">
<cfif rdate is "" and rdate2 is "">
<cfquery name="addsendrecord" datasource="#session.dsname#" username="#session.dsnusername#" password="#session.dsnpassword#">
insert into tblsendemail (sendto, sendfrom, sendsubject, sendattach, sendmessage, senddate, schoolid, sendbcc)
values ('#email3#;#Email1038#', 'no-reply@bodwell.edu', N'Attendance reminder on #dateformat(now(), "yyyy-mm-dd")#', '', N'Dear #firstname#,<br><br>According to our records, we did not receive an attendance report for #subjectname# today. Please submit the attendance report accordingly.<br><br><br>This message is automatically generated by Bodwell database system.', #now()#, 'AR#url.theperiod#', '')
</cfquery>
</cfif>
</cfoutput>
</cfif>
</cfif>
</cfif>
</cfif>
