<?php
require_once __DIR__.'/sendEmailClass.php';

date_default_timezone_set('America/Vancouver');
$thedate = date("Y-m-d");

$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$pdo = new PDO($dsn);

// Get semester
$stmt = $pdo->query("SELECT startdate, enddate FROM tblbhssemester WHERE currentsemester = 'Y'");
$semester = $stmt->fetch(PDO::FETCH_ASSOC);
$startDate = $semester['startdate'];
$endDate = $semester['enddate'];

// Query detention records by hadvisor
$sql = "
SELECT s.StudentID, s.FirstName, s.LastName, s.EnglishName, l.RDate, l.DetentionNeeded, l.DetentionServed,
       l.RRComment, h.Halls, h.RoomNo, h.HAdvisor, h.HAdvisor2, t.Email3
FROM tblbhsstudent s
JOIN tblbhsdormdailylog l ON s.StudentID = l.StudentID
JOIN tblbhshomestay h ON h.StudentID = s.StudentID
JOIN tblstaff t ON h.HAdvisor = t.FirstName + ' ' + t.LastName
WHERE t.SchoolID IN ('BHS','BSS') AND t.Email3 <> '' AND t.CurrentStaff = 'Y'
  AND l.DetentionNeeded = ?
GROUP BY h.HAdvisor, s.FirstName, s.LastName, s.EnglishName, s.StudentID,
         l.RDate, l.DetentionNeeded, l.DetentionServed, l.RRComment,
         h.Halls, h.RoomNo, h.HAdvisor2, t.Email3
";
$stmt = $pdo->prepare($sql);
$stmt->execute([$thedate]);
$data = $stmt->fetchAll(PDO::FETCH_ASSOC);

$grouped = [];
foreach ($data as $row) {
    $grouped[$row['HAdvisor']][] = $row;
}

foreach ($grouped as $advisor => $rows) {
    $email1 = $rows[0]['Email3'];
    $advisor2 = $rows[0]['HAdvisor2'];

    $stmt2 = $pdo->prepare("SELECT Email3 FROM tblstaff WHERE SchoolID IN ('BHS','BSS') AND CurrentStaff = 'Y' AND FirstName + ' ' + LastName = ?");
    $stmt2->execute([$advisor2]);
    $result = $stmt2->fetch(PDO::FETCH_ASSOC);
    $email2 = $result ? $result['Email3'] : '';

    $html = '<table border="1" cellspacing="0" cellpadding="0" style="font-size:8pt;font-family:Verdana" bordercolor="#000000">';
    $html .= '<tr style="font-weight:bold;" align="center"><td>#</td><td>Student Name</td><td>Halls</td><td>Room</td><td>Curfew missed</td><td>Detention served</td><td>Total curfew missed and no detention served</td></tr>';

    foreach ($rows as $index => $r) {
        $stmt3 = $pdo->prepare("
            SELECT RDate FROM tblbhsdormdailylog
            WHERE StudentID = ? AND RDate BETWEEN ? AND ? AND DetentionNeeded IS NOT NULL
            ORDER BY RDate
        ");
        $stmt3->execute([$r['StudentID'], $startDate, $endDate]);
        $missed = $stmt3->fetchAll(PDO::FETCH_COLUMN);

        $missedFormatted = implode(', ', array_map(fn($d) => date("Mj", strtotime($d)), $missed));
        $html .= '<tr>';
        $html .= '<td>' . ($index + 1) . '.</td>';
        $html .= '<td>' . strtoupper($r['LastName']) . ', ' . $r['FirstName'];
        if (!empty($r['EnglishName'])) $html .= ' (' . $r['EnglishName'] . ')';
        $html .= '</td>';
        $html .= '<td>' . $r['Halls'] . '</td>';
        $html .= '<td align="center">' . $r['RoomNo'] . '</td>';
        $html .= '<td align="center">' . date("M j", strtotime($r['RDate'])) . '</td>';
        $html .= '<td align="center">' . ($r['DetentionServed'] == 1 ? 'YES' : 'NO') . '</td>';
        $html .= '<td>' . $missedFormatted . '</td>';
        $html .= '</tr>';
    }

    $html .= '</table><br>This message is automatically generated by Bodwell database system.';

    sendEmail(
        ['email' => 'boarding@bodwell.edu', 'name' => 'Boarding Department'],
        [['email' => $email1, 'name' => $advisor], ['email' => $email2, 'name' => $advisor2]],
        [],
        "Detention attendance on $thedate",
        $html
    );
}

// Send summary to Stephen and Admin
$stmt = $pdo->prepare("
SELECT s.StudentID, s.FirstName, s.LastName, s.EnglishName, l.RDate, l.DetentionNeeded,
       l.DetentionServed, l.RRComment, h.Halls, h.RoomNo
FROM tblbhsstudent s
JOIN tblbhsdormdailylog l ON s.StudentID = l.StudentID
JOIN tblbhshomestay h ON h.StudentID = s.StudentID
WHERE l.DetentionNeeded = ?
ORDER BY l.DetentionServed, h.Halls, s.LastName, s.FirstName
");
$stmt->execute([$thedate]);
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

if ($rows) {
    $html = '<table border="1" cellspacing="0" cellpadding="0" style="font-size:8pt;font-family:Verdana" bordercolor="#000000">';
    $html .= '<tr style="font-weight:bold;" align="center"><td>#</td><td>Student Name</td><td>Halls</td><td>Room</td><td>Curfew missed</td><td>Detention served</td><td>Total curfew missed and no detention served</td></tr>';

    foreach ($rows as $index => $r) {
        $stmt3 = $pdo->prepare("
            SELECT RDate FROM tblbhsdormdailylog
            WHERE StudentID = ? AND RDate BETWEEN ? AND ? AND DetentionNeeded IS NOT NULL
            ORDER BY RDate
        ");
        $stmt3->execute([$r['StudentID'], $startDate, $endDate]);
        $missed = $stmt3->fetchAll(PDO::FETCH_COLUMN);
        $missedFormatted = implode(', ', array_map(fn($d) => date("Mj", strtotime($d)), $missed));

        $html .= '<tr>';
        $html .= '<td>' . ($index + 1) . '.</td>';
        $html .= '<td>' . strtoupper($r['LastName']) . ', ' . $r['FirstName'];
        if (!empty($r['EnglishName'])) $html .= ' (' . $r['EnglishName'] . ')';
        $html .= '</td>';
        $html .= '<td>' . $r['Halls'] . '</td>';
        $html .= '<td align="center">' . $r['RoomNo'] . '</td>';
        $html .= '<td align="center">' . date("M j", strtotime($r['RDate'])) . '</td>';
        $html .= '<td align="center">' . ($r['DetentionServed'] == 1 ? 'YES' : 'NO') . '</td>';
        $html .= '<td>' . $missedFormatted . '</td>';
        $html .= '</tr>';
    }

    $html .= '</table><br>This message is automatically generated by Bodwell database system.';

    sendEmail(
        ['email' => 'boarding@bodwell.edu', 'name' => 'Boarding Department'],
        [['email' => 'sgoobie@bodwell.edu', 'name' => 'Stephen Goobie'], ['email' => 'boardingadmin@bodwell.edu', 'name' => 'Boarding Admin']],
        [],
        "Detention attendance on $thedate",
        $html
    );
}
?>
