<!--- schedule to send out the STUDY HALL report at 5:10am the next day
Send to counselors
Send to the 2 hall advisors for each hall
Send to boarding admin + 1047 --->
<!--- For last day --->
<cfset thedate = parsedatetime("#dateformat(dateadd("d", -1, now()), "mm/dd/yyyy")#")>
<cfinclude template="../inc_email.cfm">
<cfquery name="getsemester" datasource="#session.dsname#" username="#session.dsnusername#" password="#session.dsnpassword#">
select * from tblbhssemester where currentsemester = 'Y'
</cfquery>
<cfquery name="getdata" datasource="#session.dsname#" username="#session.dsnusername#" password="#session.dsnpassword#">
select tblbhsstudent.studentid, tblbhsstudent.firstname, tblbhsstudent.lastname, tblbhsstudent.englishname, tblbhsstudent.counselor, tblbhshomestay.hadvisor, tblbhshomestay.hadvisor2, tblbhshomestay.tutor, tblbhshomestay.sundaygroup, tblbhsdormdailylog.rcomment, tblbhsdormdailylog.hacomment, tblbhsdormdailylog.rstudy, tblbhsdormdailylog.rmeet, tblstaff.email3 from tblbhsstudent, tblbhsdormdailylog, tblbhshomestay, tblstaff where tblbhsstudent.studentid = tblbhsdormdailylog.studentid and tblbhshomestay.studentid = tblbhsstudent.studentid and tblbhsstudent.counselor = tblstaff.firstname + ' ' + tblstaff.lastname and tblstaff.schoolid in ('BHS','BSS') and tblstaff.email3 <> '' and tblstaff.currentstaff = 'Y' and rdate = #thedate# and studygroup = 'S' and (rstudy = 1 or rmeet = 1 or rcomment <> '') and (tblbhsdormdailylog.sblock is null or tblbhsdormdailylog.sblock <> '6:00') group by tblbhsstudent.counselor, tblbhshomestay.hadvisor, tblbhshomestay.tutor, tblbhsstudent.firstname, tblbhsstudent.lastname, tblbhsstudent.englishname, tblbhsstudent.studentid, tblbhsdormdailylog.rcomment, tblbhsdormdailylog.hacomment, tblbhsdormdailylog.rstudy, tblbhsdormdailylog.rmeet, tblbhshomestay.sundaygroup, tblbhshomestay.hadvisor2, tblstaff.email3
</cfquery>
<!--- Send to counselors --->
<cfoutput query="getdata" group="counselor">
<cfmail from="no-reply@bodwell.edu" to="#email3#" server="#session.emailserver#" port="#session.emailport#" useSSL="#session.emailuseSSL#" username="#session.emailusername#" password="#session.emailpassword#" subject="STUDY HALL Report on #dateformat(thedate, 'mmmm, dd, yyyy')#" type="HTML">
Here is the STUDY HALL Report on #dateformat(thedate, "mmmm, dd, yyyy")#:<br><br>
Counselor: #counselor#,<br><br>
<table border="1" cellspacing="0" cellpadding="3" style="font-size:8pt;font-family:Verdana" bordercolor="##000000">
<tr><td>Student</td><td>Hall Advisor</td><td>Tutor</td><td>PRESENT/ABSENT</td><td>## OF ABSENCES</td><td>TUTOR ASSESSMENT</td><td width="250">Tutor comment</td><td width="250">Advisor comment</td></tr>
<cfoutput>
<cfif rstudy is 1><cfquery name="getdata5" datasource="#session.dsname#" username="#session.dsnusername#" password="#session.dsnpassword#">
select count(rstudy) as ttlstudyabsence from tblbhsdormdailylog where studentid = #studentid# and studygroup = 'S' and rdate >= #parsedatetime(getsemester.startdate)# and rdate <= #parsedatetime(getsemester.enddate)# and rstudy = 1 and (tblbhsdormdailylog.sblock is null or tblbhsdormdailylog.sblock <> '6:00')
</cfquery></cfif>
<tr><td>#lastname#, #firstname#<cfif englishname neq ""> (#englishname#)</cfif></td><td>#hadvisor#/#hadvisor2#</td><td>#tutor#</td><td align="center"><cfif rstudy is 1>Unexcused Absent<cfelseif rstudy is 5>Present<cfelseif rstudy is 0>Excused Absent<cfelseif rstudy is 2>Late 5 mins</cfif></td><td align="center"><cfif rstudy is 1><cfif int(getdata5.ttlstudyabsence) is 1>1st<cfelseif int(getdata5.ttlstudyabsence) is 2>2nd<cfelseif int(getdata5.ttlstudyabsence) is 3>3rd<cfelse>#int(getdata5.ttlstudyabsence)#th</cfif><cfelse>&nbsp;</cfif></td><td><cfif rmeet is 0>N/A<cfelseif rmeet is 1>Needs improvement<cfelseif rmeet is 5>Meets expectations</cfif></td><td>#rcomment#&nbsp;</td><td>#hacomment#&nbsp;</td></tr>
</cfoutput>
</table>
<br>This report is automatically generated by STUDY HALL report system.
</cfmail>
</cfoutput>
<cfquery name="getdata" datasource="#session.dsname#" username="#session.dsnusername#" password="#session.dsnpassword#">
select tblbhsstudent.studentid, tblbhsstudent.firstname, tblbhsstudent.lastname, tblbhsstudent.englishname, tblbhsstudent.counselor, tblbhshomestay.hadvisor, tblbhshomestay.hadvisor2, tblbhshomestay.tutor, tblbhshomestay.sundaygroup, tblbhsdormdailylog.rcomment, tblbhsdormdailylog.hacomment, tblbhsdormdailylog.rstudy, tblbhsdormdailylog.rmeet, tblstaff.email3 from tblbhsstudent, tblbhsdormdailylog, tblbhshomestay, tblstaff where tblbhsstudent.studentid = tblbhsdormdailylog.studentid and tblbhshomestay.studentid = tblbhsstudent.studentid and tblbhshomestay.hadvisor = tblstaff.firstname + ' ' + tblstaff.lastname and tblstaff.schoolid in ('BHS','BSS') and tblstaff.email3 <> '' and tblstaff.currentstaff = 'Y' and tblbhsdormdailylog.rdate = #thedate# and tblbhsdormdailylog.studygroup = 'S' and (tblbhsdormdailylog.rstudy = 1 or tblbhsdormdailylog.rmeet = 1 or tblbhsdormdailylog.rcomment <> '') and (tblbhsdormdailylog.sblock is null or tblbhsdormdailylog.sblock <> '6:00') group by tblbhshomestay.hadvisor, tblbhsstudent.counselor, tblbhshomestay.tutor, tblbhsstudent.firstname, tblbhsstudent.lastname, tblbhsstudent.englishname, tblbhsstudent.studentid, tblbhsdormdailylog.rcomment, tblbhsdormdailylog.hacomment, tblbhsdormdailylog.rstudy, tblbhsdormdailylog.rmeet, tblbhshomestay.sundaygroup, tblbhshomestay.hadvisor2, tblstaff.email3
</cfquery>
<!--- Send to the 2 hall advisors for each hall --->
<cfoutput query="getdata" group="hadvisor">
<!--- get hall advisor 2 email address --->
<cfquery name="gethadvisor2" datasource="#session.dsname#" username="#session.dsnusername#" password="#session.dsnpassword#">
select email3 from tblstaff where schoolid in ('BHS','BSS') and currentstaff = 'Y' and department in ('5','6') and firstname + ' ' + lastname = '#trim(hadvisor2)#'
</cfquery>
<cfmail from="no-reply@bodwell.edu" to="#email3#;#gethadvisor2.email3#" server="#session.emailserver#" port="#session.emailport#" useSSL="#session.emailuseSSL#" username="#session.emailusername#" password="#session.emailpassword#" subject="STUDY HALL Report on #dateformat(thedate, 'mmmm, dd, yyyy')#" type="HTML">
Here is the STUDY HALL Report on #dateformat(thedate, "mmmm, dd, yyyy")#.<br><br>
Youth advisor: #hadvisor#/#hadvisor2#,<br><br>
<table border="1" cellspacing="0" cellpadding="3" style="font-size:8pt;font-family:Verdana" bordercolor="##000000">
<tr><td>Student</td><td>Counselor</td><td>Tutor</td><td>PRESENT/ABSENT</td><td>## OF ABSENCES</td><td>TUTOR ASSESSMENT</td><td width="250">Tutor comment</td><td width="250">Advisor comment</td></tr>
<cfoutput>
<cfif rstudy is 1><cfquery name="getdata5" datasource="#session.dsname#" username="#session.dsnusername#" password="#session.dsnpassword#">
select count(rstudy) as ttlstudyabsence from tblbhsdormdailylog where studentid = #studentid# and studygroup = 'S' and rdate >= #parsedatetime(getsemester.startdate)# and rdate <= #parsedatetime(getsemester.enddate)# and rstudy = 1 and (tblbhsdormdailylog.sblock is null or tblbhsdormdailylog.sblock <> '6:00')
</cfquery></cfif>
<tr><td>#lastname#, #firstname#<cfif englishname neq ""> (#englishname#)</cfif></td><td>#counselor#</td><td>#tutor#</td><td align="center"><cfif rstudy is 1>Unexcused Absent<cfelseif rstudy is 5>Present<cfelseif rstudy is 0>Excused Absent<cfelseif rstudy is 2>Late 5 mins</cfif></td><td align="center"><cfif rstudy is 1><cfif int(getdata5.ttlstudyabsence) is 1>1st<cfelseif int(getdata5.ttlstudyabsence) is 2>2nd<cfelseif int(getdata5.ttlstudyabsence) is 3>3rd<cfelse>#int(getdata5.ttlstudyabsence)#th</cfif><cfelse>&nbsp;</cfif></td><td><cfif rmeet is 0>N/A<cfelseif rmeet is 1>Needs improvement<cfelseif rmeet is 5>Meets expectations</cfif></td><td>#rcomment#&nbsp;</td><td>#hacomment#&nbsp;</td></tr>
</cfoutput>
</table>
<br>This report is automatically generated by STUDY HALL report system.
</cfmail>
</cfoutput>
<cfquery name="getdata" datasource="#session.dsname#" username="#session.dsnusername#" password="#session.dsnpassword#">
select tblbhsstudent.studentid, tblbhsstudent.firstname, tblbhsstudent.lastname, tblbhsstudent.englishname, tblbhsstudent.counselor, tblbhsstudent.currentgrade, tblbhshomestay.hadvisor, tblbhshomestay.hadvisor2, tblbhshomestay.tutor, tblbhshomestay.sundaygroup, tblbhsdormdailylog.rcomment, tblbhsdormdailylog.hacomment, tblbhsdormdailylog.rmeet, tblbhsdormdailylog.rstudy from tblbhsstudent, tblbhsdormdailylog, tblbhshomestay where tblbhsstudent.studentid = tblbhsdormdailylog.studentid and tblbhshomestay.studentid = tblbhsstudent.studentid and rdate = #thedate# and studygroup = 'S' and (rstudy = 1 or rmeet = 1 or rcomment <> '') and (tblbhsdormdailylog.sblock is null or tblbhsdormdailylog.sblock <> '6:00') order by tblbhsdormdailylog.rstudy, tblbhsstudent.lastname, tblbhsstudent.firstname, tblbhsstudent.englishname, tblbhshomestay.hadvisor, tblbhsstudent.counselor, tblbhshomestay.tutor, tblbhsdormdailylog.rcomment, tblbhshomestay.sundaygroup
</cfquery>
<cfif getdata.recordcount gt 0>
<!--- Send to boarding admin + 1047 --->
<cfset emaillist = "#BAemail#;#Email1047#">
<cfmail from="no-reply@bodwell.edu" to="#emaillist#" server="#session.emailserver#" port="#session.emailport#" useSSL="#session.emailuseSSL#" username="#session.emailusername#" password="#session.emailpassword#" subject="STUDY HALL Report on #dateformat(thedate, 'mmmm, dd, yyyy')#" type="HTML">
Here is the STUDY HALL Report on #dateformat(thedate, "mmmm, dd, yyyy")#.<br><br>
<table border="1" cellspacing="0" cellpadding="3" style="font-size:8pt;font-family:Verdana" bordercolor="##000000">
<tr><td>Student</td><td>Current Grade</td><td>Counselor</td><td>Youth Advisor</td><td>Tutor</td><td>PRESENT/ABSENT</td><td>## OF ABSENCES</td><td>TUTOR ASSESSMENT</td><td width="250">Tutor comment</td><td width="250">Advisor comment</td></tr>
<cfloop query="getdata">
<cfif rstudy is 1><cfquery name="getdata5" datasource="#session.dsname#" username="#session.dsnusername#" password="#session.dsnpassword#">
select count(rstudy) as ttlstudyabsence from tblbhsdormdailylog where studentid = #studentid# and studygroup = 'S' and rdate >= #parsedatetime(getsemester.startdate)# and rdate <= #parsedatetime(getsemester.enddate)# and rstudy = 1 and (tblbhsdormdailylog.sblock is null or tblbhsdormdailylog.sblock <> '6:00')
</cfquery></cfif>
<tr><td>#lastname#, #firstname#<cfif englishname neq ""> (#englishname#)</cfif></td><td>#currentgrade#</td><td>#counselor#</td><td>#hadvisor#/#hadvisor2#</td><td>#tutor#</td><td align="center"><cfif rstudy is 1>Unexcused Absent<cfelseif rstudy is 5>Present<cfelseif rstudy is 0>Excused Absent<cfelseif rstudy is 2>Late 5 mins</cfif></td><td align="center"><cfif rstudy is 1><cfif int(getdata5.ttlstudyabsence) is 1>1st<cfelseif int(getdata5.ttlstudyabsence) is 2>2nd<cfelseif int(getdata5.ttlstudyabsence) is 3>3rd<cfelse>#int(getdata5.ttlstudyabsence)#th</cfif><cfelse>&nbsp;</cfif></td><td><cfif rmeet is 0>N/A<cfelseif rmeet is 1>Needs improvement<cfelseif rmeet is 5>Meets expectations</cfif></td><td>#rcomment#&nbsp;</td><td>#hacomment#&nbsp;</td></tr>
</cfloop>
</table>
<br>This report is automatically generated by STUDY HALL report system.
</cfmail>
</cfif>
