<?php
require_once __DIR__.'/sendEmailClass.php';

$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$conn = new PDO($dsn);

// Today's and yesterday's date
$thedate = date('Y-m-d');
$yesterday = date('Y-m-d', strtotime('-1 day'));

// Query students with sick report today
$sql = "SELECT s.StudentID, s.FirstName, s.LastName, s.EnglishName, s.Counselor,
               h.RoomNo, h.HAdvisor, h.HAdvisor2, h.Tutor,
               d.LateSick, d.LSComment,
               st.Email3
        FROM tblbhsstudent s
        JOIN tblbhsdormdailylog d ON s.StudentID = d.StudentID
        JOIN tblbhshomestay h ON h.StudentID = s.StudentID
        JOIN tblstaff st ON st.FirstName + ' ' + st.LastName = h.HAdvisor
        WHERE st.SchoolID IN ('BHS', 'BSS') AND st.CurrentStaff = 'Y' AND st.Email3 <> ''
          AND d.RDate = ? AND d.LateSick <> ''
        GROUP BY h.HAdvisor, s.Counselor, h.Tutor, s.FirstName, s.LastName, s.EnglishName,
                 s.StudentID, d.LSComment, d.LateSick, h.RoomNo, st.Email3, h.HAdvisor2";
$stmt = $conn->prepare($sql);
$stmt->execute([$thedate]);
$records = $stmt->fetchAll(PDO::FETCH_ASSOC);

if (count($records) > 0) {
    // Group by HAdvisor
    $grouped = [];
    foreach ($records as $row) {
        $grouped[$row['HAdvisor']][] = $row;
    }

    foreach ($grouped as $advisor => $students) {
        $email = $students[0]['Email3'];
        $advisor2 = $students[0]['HAdvisor2'];

        // Get HAdvisor2 email
        $stmt2 = $conn->prepare("SELECT Email3 FROM tblstaff WHERE SchoolID IN ('BHS','BSS') AND CurrentStaff = 'Y' AND FirstName + ' ' + LastName = ?");
        $stmt2->execute([$advisor2]);
        $row2 = $stmt2->fetch(PDO::FETCH_ASSOC);
        $email2 = $row2 ? $row2['Email3'] : '';

        // Build table
        $html = "<p>Here is the Sick Report on " . date('F d, Y', strtotime($thedate)) . ".</p>";
        $html .= "<p>Hall advisor: {$advisor}/{$advisor2},</p>";
        $html .= '<table border="1" cellspacing="0" cellpadding="3" style="font-size:8pt;font-family:Verdana" bordercolor="#000000">';
        $html .= "<tr><td>Student</td><td>Room ##</td><td>Counselor</td><td>Hall Advisor</td><td>Bedtime Mark<br>last night</td><td>Bedtime Comment<br>last night</td><td>Sick</td><td>Comment</td></tr>";

        foreach ($students as $student) {
            $stmt3 = $conn->prepare("SELECT RCurfew, RRComment FROM tblbhsdormdailylog
                                     WHERE StudentID = ? AND RDate = ?");
            $stmt3->execute([$student['StudentID'], $yesterday]);
            $bedtime = $stmt3->fetch(PDO::FETCH_ASSOC);

            $rcurfew = '';
            $rrcomment = '';
            if ($bedtime && isset($bedtime['RCurfew'])) {
                $rcurfew = $bedtime['RCurfew'];
            }

            if ($rrcomment && isset($bedtime['RRComment'])) {
                $rrcomment = $bedtime['RRComment'];
            }


            $mark = ($rcurfew == 1) ? 'Needs improvement' : (($rcurfew == 5) ? 'Meets expectations' : '');

            $sickLabel = ($student['LateSick'] == 'NonS') ? 'Sick' : $student['LateSick'];
            $html .= "<tr><td>{$student['LastName']}, {$student['FirstName']}";
            if (!empty($student['EnglishName'])) $html .= " ({$student['EnglishName']})";
            $html .= "</td><td>{$student['RoomNo']}</td><td>{$student['Counselor']}</td><td>{$advisor}/{$advisor2}</td>
                      <td align='center'>{$mark}</td><td>{$rrcomment}&nbsp;</td><td align='center'>{$sickLabel}</td><td>{$student['LSComment']}&nbsp;</td></tr>";
        }

        $html .= "</table><br>This report is automatically generated by Sick report system.";

        sendEmail(
            ['email' => 'boarding@bodwell.edu', 'name' => 'Boarding Department'],
            [['email' => $email, 'name' => $advisor], ['email' => $email2, 'name' => $advisor2]],
            [],
            "Sick Report on " . date('F d, Y', strtotime($thedate)),
            $html
        );
    }

    // Summary email
    $html = "<p>Here is the Sick Report on " . date('F d, Y', strtotime($thedate)) . ".</p>";
    $html .= '<table border="1" cellspacing="0" cellpadding="3" style="font-size:8pt;font-family:Verdana" bordercolor="#000000">';
    $html .= "<tr><td>Student</td><td>Room ##</td><td>Counselor</td><td>Hall Advisor</td><td>Bedtime Mark<br>last night</td><td>Bedtime Comment<br>last night</td><td>Sick</td><td>Comment</td></tr>";

    foreach ($records as $row) {
        $stmt3 = $conn->prepare("SELECT RCurfew, RRComment FROM tblbhsdormdailylog
                                 WHERE StudentID = ? AND RDate = ?");
        $stmt3->execute([$row['StudentID'], $yesterday]);
        $bedtime = $stmt3->fetch(PDO::FETCH_ASSOC);
        $rcurfew = '';
        $rrcomment = '';
        if ($bedtime && isset($bedtime['RCurfew'])) {
            $rcurfew = $bedtime['RCurfew'];
        }

        if ($rrcomment && isset($bedtime['RRComment'])) {
            $rrcomment = $bedtime['RRComment'];
        }

        $mark = ($rcurfew == 1) ? 'Needs improvement' : (($rcurfew == 5) ? 'Meets expectations' : '');
        $sickLabel = ($row['LateSick'] == 'NonS') ? 'Sick' : $row['LateSick'];

        $html .= "<tr><td>{$row['LastName']}, {$row['FirstName']}";
        if (!empty($row['EnglishName'])) $html .= " ({$row['EnglishName']})";
        $html .= "</td><td>{$row['RoomNo']}</td><td>{$row['Counselor']}</td><td>{$row['HAdvisor']}";
        if (!empty($row['HAdvisor'])) $html .= '/';
        $html .= "{$row['HAdvisor2']}</td><td align='center'>{$mark}</td><td>{$rrcomment}&nbsp;</td><td align='center'>{$sickLabel}</td><td>{$row['LSComment']}&nbsp;</td></tr>";
    }

    $html .= "</table><br>This report is automatically generated by Sick report system.";

    sendEmail(
        ['email' => 'no-reply@bodwell.edu', 'name' => 'Bodwell System'],
        [['email' => 'sgoobie@bodwell.edu', 'name' => 'S. Goobie'], ['email' => 'admin@bodwell.edu', 'name' => 'Admin']],
        [],
        "Sick Report on " . date('F d, Y', strtotime($thedate)),
        $html
    );
}
?>
