<?php
require_once __DIR__.'/sendEmailClass.php';

$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$pdo = new PDO($dsn);

$thedate = date('Y-m-d');
$yesterday = date('Y-m-d', strtotime('-1 day'));

$htmlGroup = [];

$query = "
    SELECT s.StudentID, s.FirstName, s.LastName, s.EnglishName, s.Counselor,
           h.RoomNo, h.HAdvisor, h.HAdvisor2, h.Tutor,
           d.LateSick, d.LSComment, st.Email3
    FROM tblBHSStudent s
    JOIN tblBHSDormDailyLog d ON s.StudentID = d.StudentID
    JOIN tblBHSHomestay h ON s.StudentID = h.StudentID
    JOIN tblStaff st ON h.HAdvisor = st.FirstName + ' ' + st.LastName
    WHERE d.RDate = ?
      AND d.LateSick IS NOT NULL AND d.LateSick <> ''
      AND st.SchoolID IN ('BHS','BSS')
      AND st.Email3 IS NOT NULL AND st.Email3 <> ''
      AND st.CurrentStaff = 'Y'
";
$stmt = $pdo->prepare($query);
$stmt->execute([$thedate]);
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

foreach ($rows as $row) {
    $advisor = $row['HAdvisor'];
    $groupKey = $advisor;
    if (!isset($htmlGroup[$groupKey])) {
        $htmlGroup[$groupKey] = [
            'to' => [$row['Email3']],
            'html' => "Here is the Sick Report on " . date('F d, Y', strtotime($thedate)) . "<br><br>Hall advisor: {$row['HAdvisor']}/{$row['HAdvisor2']}<br><br>",
            'table' => ''
        ];
    }

    $stmt2 = $pdo->prepare("SELECT RRComment, RCurfew FROM tblBHSDormDailyLog WHERE RDate = ? AND StudentID = ?");
    $stmt2->execute([$yesterday, $row['StudentID']]);
    $bedtime = $stmt2->fetch(PDO::FETCH_ASSOC);

    $rcurfew = '';
    $rrcomment = '';
    if ($bedtime && isset($bedtime['RCurfew'])) {
        $rcurfew = $bedtime['RCurfew'];
    }
    if ($bedtime && isset($bedtime['RRComment'])) {
        $rrcomment = $bedtime['RRComment'];
    }

    $mark = '';
    if ($rcurfew == 1) {
        $mark = 'Needs improvement';
    } elseif ($rcurfew == 5) {
        $mark = 'Meets expectations';
    }

    $htmlGroup[$groupKey]['table'] .= "<tr>
        <td>{$row['LastName']}, {$row['FirstName']}" . ($row['EnglishName'] ? " ({$row['EnglishName']})" : '') . "</td>
        <td>{$row['RoomNo']}</td>
        <td>{$row['Counselor']}</td>
        <td>{$row['HAdvisor']}/{$row['HAdvisor2']}</td>
        <td align='center'>{$mark}</td>
        <td>{$rrcomment}</td>
        <td align='center'>{$row['LateSick']}</td>
        <td>{$row['LSComment']}</td>
    </tr>";
}

foreach ($htmlGroup as $advisor => $data) {
    $html = $data['html'] . "<table border='1' cellspacing='0' cellpadding='3' style='font-size:8pt;font-family:Verdana' bordercolor='#000000'>
        <tr><td>Student</td><td>Room ##</td><td>Counselor</td><td>Hall Advisor</td><td>Bedtime Mark<br>last night</td><td>Bedtime Comment<br>last night</td><td>Sick</td><td>Comment</td></tr>
        {$data['table']}
    </table>
    <br>This report is automatically generated by Sick report system.";

    sendEmail(
        ['email' => 'no-reply@bodwell.edu', 'name' => 'Bodwell Sick Report'],
        [['email' => $data['to'][0], 'name' => $advisor]],
        [],
        "Sick Report on " . date('Y-m-d', strtotime($thedate)),
        $html
    );
}
?>
