<?php
require_once __DIR__ . '/sendEmailClass.php';

$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$conn = new PDO($dsn);

// Run only if yesterday was Friday (5) or Saturday (6)
$yesterday = date('Y-m-d', strtotime('-1 day'));
$dayOfWeek = date('w', strtotime($yesterday)); // Sunday=0 ... Saturday=6

if ($dayOfWeek == 5 || $dayOfWeek == 6) {
    $sql = "
        SELECT s.FirstName, s.LastName, s.EnglishName, s.Counselor,
               h.HAdvisor, h.HAdvisor2, h.RoomNo, h.Halls,
               d.RRComment, d.RCurfew
        FROM tblbhsStudent s
        JOIN tblbhsDormDailyLog d ON s.StudentID = d.StudentID
        JOIN tblbhsHomestay h ON h.StudentID = s.StudentID
        WHERE d.RDate = ?
          AND d.RCurfew BETWEEN 1 AND 3
        ORDER BY h.Halls, h.RoomNo, s.LastName, s.FirstName, s.EnglishName
    ";
    $stmt = $conn->prepare($sql);
    $stmt->execute([$yesterday]);
    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

    if (count($rows) > 0) {
        $subject = "Curfew/Bedtime Report on " . date('F d, Y', strtotime($yesterday));
        $html = "Here is the Curfew/Bedtime Report on " . date('F d, Y', strtotime($yesterday)) . ".<br><br>";

        $html .= '<table border="1" cellspacing="0" cellpadding="3" style="font-size:8pt;font-family:Verdana" bordercolor="#000000">';
        $html .= '<tr><td>Student</td><td>Hall</td><td>Room</td><td>Counselor</td><td>Youth Advisor</td><td>Status</td><td>Comment</td></tr>';

        foreach ($rows as $row) {
            $student = "{$row['LastName']}, {$row['FirstName']}";
            if (!empty($row['EnglishName'])) {
                $student .= " ({$row['EnglishName']})";
            }

            $html .= "<tr>
                <td>{$student}</td>
                <td>{$row['Halls']}</td>
                <td>{$row['RoomNo']}</td>
                <td>{$row['Counselor']}</td>
                <td>{$row['HAdvisor']}/{$row['HAdvisor2']}</td>
                <td align='center'>Needs improvement</td>
                <td>{$row['RRComment']}&nbsp;</td>
            </tr>";
        }

        $html .= '</table><br>This report is automatically generated by Curfew/Bedtime report system.';

        $from = ['email' => 'boarding@bodwell.edu', 'name' => 'Boarding Department'];
        $to = [
            ['email' => 'sgoobie@bodwell.edu', 'name' => 'Stephen Goobie']
        ];

        // Get BAemail list (staff with GroupTeam 1038)
        $staffSql = "SELECT Email3 FROM tblStaff WHERE GroupTeam LIKE '%1038%' AND CurrentStaff = 'Y'";
        $staffStmt = $conn->query($staffSql);
        foreach ($staffStmt->fetchAll(PDO::FETCH_ASSOC) as $staff) {
            if (!empty($staff['Email3'])) {
                $to[] = ['email' => $staff['Email3'], 'name' => 'Boarding Admin'];
            }
        }

        sendEmail($from, $to, [], $subject, $html, '');
    }
}
?>
