<?php
require_once __DIR__.'/sendEmailClass.php';

$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$today = date('w');

if ($today == 0 || $today == 3) { // Sunday=0, Wednesday=3
    $thedate1 = date('Y-m-d', strtotime(($today == 3) ? '-2 days' : '-3 days'));
    $thedate2 = date('Y-m-d', strtotime(($today == 3) ? 'today' : '-2 days'));

    // Get report data
    $sql = "
    SELECT s.StudentID, s.FirstName, s.LastName, s.EnglishName, s.Counselor,
           h.RoomNo, h.HAdvisor, h.HAdvisor2, h.Tutor,
           d.Tidy1, d.RDate,
           a.Email3 AS AdvisorEmail
    FROM tblBHSStudent s
    JOIN tblBHSHomestay h ON s.StudentID = h.StudentID
    JOIN tblBHSDormDailyLog d ON s.StudentID = d.StudentID
    JOIN tblStaff a ON h.HAdvisor = a.FirstName + ' ' + a.LastName
    WHERE d.RDate >= ? AND d.RDate <= ?
      AND d.Tidy1 IS NOT NULL AND d.Tidy1 <> 5
      AND a.SchoolID IN ('BHS','BSS') AND a.Email3 <> '' AND a.CurrentStaff = 'Y'
    ORDER BY h.HAdvisor, s.LastName, s.FirstName, d.RDate";

    $stmt = $pdo->prepare($sql);
    $stmt->execute([$thedate1, $thedate2]);
    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

    $advisorData = [];
    $adminData = [];

    foreach ($rows as $r) {
        $tidyLabel = 'Needs improvement: ';
        $t = $r['Tidy1'];
        $tidyLabel .=
            (strpos($t, '3') !== false && strpos($t, '2') !== false && strpos($t, '1') !== false) ? 'Bed + Desk + Floor' :
            ((strpos($t, '3') !== false && strpos($t, '2') !== false) ? 'Bed + Desk' :
            ((strpos($t, '3') !== false && strpos($t, '1') !== false) ? 'Bed + Floor' :
            ((strpos($t, '2') !== false && strpos($t, '1') !== false) ? 'Desk + Floor' :
            (($t == '3') ? 'Bed' : (($t == '2') ? 'Desk' : 'Floor')))));

        $htmlRow = "<tr><td>{$r['LastName']}, {$r['FirstName']}" . ($r['EnglishName'] ? " ({$r['EnglishName']})" : "") . "</td>
        <td>{$r['RoomNo']}</td><td>{$r['Counselor']}</td><td>{$r['HAdvisor']}/{$r['HAdvisor2']}</td>
        <td>{$r['RDate']}</td><td>{$tidyLabel}</td></tr>";

        $advisorKey = $r['HAdvisor'] . '/' . $r['HAdvisor2'];
        $advisorData[$advisorKey]['rows'][] = $htmlRow;
        $advisorData[$advisorKey]['email'] = $r['AdvisorEmail'];
        $advisorData[$advisorKey]['HAdvisor2'] = $r['HAdvisor2'];

        $adminData[] = $htmlRow;
    }

    function getHAdvisor2Email($pdo, $name) {
        $stmt = $pdo->prepare("SELECT Email3 FROM tblStaff WHERE SchoolID IN ('BHS','BSS') AND CurrentStaff = 'Y' AND FirstName + ' ' + LastName = ?");
        $stmt->execute([trim($name)]);
        return $stmt->fetchColumn();
    }

    function sendTidinessEmail($to, $subject, $rows, $intro) {
        $html = "$intro<br><br>
        <table border='1' cellspacing='0' cellpadding='3' style='font-size:8pt;font-family:Verdana' bordercolor='#000000'>
        <tr><td>Student</td><td>Room ##</td><td>Counselor</td><td>Hall Advisor</td><td>Date</td><td>Tidiness</td></tr>
        " . implode("\n", $rows) . "</table><br>This report is automatically generated by Tidiness report system.";

        sendEmail(
            ['email' => 'boarding@bodwell.edu', 'name' => 'Boarding'],
            [['email' => $to, 'name' => 'Recipient']],
            [],
            $subject,
            $html
        );
    }

    // Send to each hall advisor group
    foreach ($advisorData as $key => $info) {
        $email1 = $info['email'];
        $email2 = getHAdvisor2Email($pdo, $info['HAdvisor2']);
        $to = "$email1;$email2";
        sendTidinessEmail($to, "Tidiness Report from $thedate1 to $thedate2", $info['rows'], "Hall advisor: $key");
    }

    // Send to all boarding admin
    $to = "sgoobie@bodwell.edu;carla.solano@bodwell.edu;boarding@bodwell.edu";
    sendTidinessEmail($to, "Tidiness Report from $thedate1 to $thedate2", $adminData, "Complete Tidiness Report from $thedate1 to $thedate2");
}
