<?php
require_once __DIR__ . '/sendEmailClass.php';

$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$conn = new PDO($dsn);
$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$thedate = date('Y-m-d', strtotime('-1 day')); // Yesterday

function sendReportEmail($from, $to, $subject, $html) {
    sendEmail($from, $to, [], $subject, $html, '');
}

// ========== HALL ADVISORS ==========
$sql = "SELECT s.StudentID, s.FirstName, s.LastName, s.EnglishName, s.Counselor,
               h.HAdvisor, h.HAdvisor2, h.Tutor, d.RRComment, d.RCurfew, st.Email3
        FROM tblBHSStudent s
        JOIN tblBHSDormDailyLog d ON s.StudentID = d.StudentID
        JOIN tblBHSHomestay h ON h.StudentID = s.StudentID
        JOIN tblStaff st ON h.HAdvisor = st.FirstName + ' ' + st.LastName
        WHERE st.SchoolID IN ('BHS','BSS') AND st.Email3 <> '' AND st.CurrentStaff = 'Y'
              AND d.RDate = ? AND d.RCurfew BETWEEN 1 AND 3
        GROUP BY h.HAdvisor, s.Counselor, h.Tutor, s.FirstName, s.LastName, s.EnglishName, s.StudentID,
                 d.RRComment, d.RCurfew, st.Email3, h.HAdvisor2";
$stmt = $conn->prepare($sql);
$stmt->execute([$thedate]);
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Group by HAdvisor
$groupedByAdvisor = [];
foreach ($rows as $row) {
    $groupedByAdvisor[$row['HAdvisor']][] = $row;
}

foreach ($groupedByAdvisor as $hadvisor => $students) {
    $email1 = $students[0]['Email3'];
    $hadvisor2 = $students[0]['HAdvisor2'];

    // Fetch HAdvisor2 email
    $stmt2 = $conn->prepare("SELECT Email3 FROM tblStaff WHERE CurrentStaff = 'Y' AND SchoolID IN ('BHS','BSS') AND FirstName + ' ' + LastName = ?");
    $stmt2->execute([$hadvisor2]);
    $advisor2Email = $stmt2->fetchColumn();

    $to = [];
    if ($email1) $to[] = ['email' => $email1, 'name' => $hadvisor];
    if ($advisor2Email) $to[] = ['email' => $advisor2Email, 'name' => $hadvisor2];

    $subject = "Curfew/Bedtime Report on " . date('F d, Y', strtotime($thedate));
    $body = "Here is the Curfew/Bedtime Report on " . date('F d, Y', strtotime($thedate)) . ".<br><br>";
    $body .= "Youth advisor: {$hadvisor}" . ($hadvisor2 ? ", {$hadvisor2}" : "") . "<br><br>";
    $body .= '<table border="1" cellspacing="0" cellpadding="3" style="font-size:8pt;font-family:Verdana">';
    $body .= "<tr><td>Student</td><td>Counselor</td><td>Status</td><td>Comment</td></tr>";

    foreach ($students as $s) {
        $name = "{$s['LastName']}, {$s['FirstName']}" . ($s['EnglishName'] ? " ({$s['EnglishName']})" : "");
        $body .= "<tr><td>{$name}</td><td>{$s['Counselor']}</td><td align='center'>Needs improvement</td><td>{$s['RRComment']}</td></tr>";
    }

    $body .= "</table><br>This report is automatically generated by Curfew/Bedtime report system.";
    sendReportEmail(['email' => 'boarding@bodwell.edu', 'name' => 'Boarding'], $to, $subject, $body);
}

// ========== COUNSELORS ==========
$sql = "SELECT s.StudentID, s.FirstName, s.LastName, s.EnglishName, s.Counselor,
               h.HAdvisor, h.HAdvisor2, h.Tutor, d.RRComment, d.RCurfew, st.Email3
        FROM tblBHSStudent s
        JOIN tblBHSDormDailyLog d ON s.StudentID = d.StudentID
        JOIN tblBHSHomestay h ON h.StudentID = s.StudentID
        JOIN tblStaff st ON s.Counselor = st.FirstName + ' ' + st.LastName
        WHERE st.SchoolID IN ('BHS','BSS') AND st.Email3 <> '' AND st.CurrentStaff = 'Y'
              AND d.RDate = ? AND d.RCurfew BETWEEN 1 AND 3
        GROUP BY s.Counselor, h.HAdvisor, h.Tutor, s.FirstName, s.LastName, s.EnglishName, s.StudentID,
                 d.RRComment, d.RCurfew, st.Email3, h.HAdvisor2";
$stmt = $conn->prepare($sql);
$stmt->execute([$thedate]);
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Group by Counselor
$groupedByCounselor = [];
foreach ($rows as $row) {
    $groupedByCounselor[$row['Counselor']][] = $row;
}

foreach ($groupedByCounselor as $counselor => $students) {
    $email = $students[0]['Email3'];
    if (!$email) continue;

    $subject = "Curfew/Bedtime Report on " . date('F d, Y', strtotime($thedate));
    $body = "Here is the Curfew/Bedtime Report on " . date('F d, Y', strtotime($thedate)) . ".<br><br>";
    $body .= '<table border="1" cellspacing="0" cellpadding="3" style="font-size:8pt;font-family:Verdana">';
    $body .= "<tr><td>Student</td><td>Youth Advisor</td><td>Status</td><td>Comment</td></tr>";

    foreach ($students as $s) {
        $name = "{$s['LastName']}, {$s['FirstName']}" . ($s['EnglishName'] ? " ({$s['EnglishName']})" : "");
        $body .= "<tr><td>{$name}</td><td>{$s['HAdvisor']}/{$s['HAdvisor2']}</td><td align='center'>Needs improvement</td><td>{$s['RRComment']}</td></tr>";
    }

    $body .= "</table><br>This report is automatically generated by Curfew/Bedtime report system.";
    sendReportEmail(['email' => 'boarding@bodwell.edu', 'name' => 'Boarding'], [['email' => $email, 'name' => $counselor]], $subject, $body);
}

// ========== BOARDING ADMIN ==========
$sql = "SELECT s.StudentID, s.FirstName, s.LastName, s.EnglishName, s.Counselor,
               h.HAdvisor, h.HAdvisor2, h.Tutor, d.RRComment, d.RCurfew
        FROM tblBHSStudent s
        JOIN tblBHSDormDailyLog d ON s.StudentID = d.StudentID
        JOIN tblBHSHomestay h ON h.StudentID = s.StudentID
        WHERE d.RDate = ? AND d.RCurfew BETWEEN 1 AND 3
        ORDER BY d.RCurfew, s.LastName, s.FirstName, s.EnglishName, h.HAdvisor, s.Counselor, h.Tutor, d.RRComment";
$stmt = $conn->prepare($sql);
$stmt->execute([$thedate]);
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

if (count($rows) > 0) {
    $stmt = $conn->query("SELECT FirstName, LastName, Email3 FROM tblStaff WHERE GroupTeam LIKE '%1026%' AND CurrentStaff = 'Y'");
    $adminEmails = [];
    foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) as $admin) {
        if ($admin['Email3']) {
            $adminEmails[] = ['email' => $admin['Email3'], 'name' => "{$admin['FirstName']} {$admin['LastName']}"];
        }
    }
    $adminEmails[] = ['email' => 'sgoobie@bodwell.edu', 'name' => 'Stephen Goobie'];

    $subject = "Curfew/Bedtime Report on " . date('F d, Y', strtotime($thedate));
    $body = "Here is the Curfew/Bedtime Report on " . date('F d, Y', strtotime($thedate)) . ".<br><br>";
    $body .= '<table border="1" cellspacing="0" cellpadding="3" style="font-size:8pt;font-family:Verdana">';
    $body .= "<tr><td>Student</td><td>Counselor</td><td>Hall Advisor</td><td>Status</td><td>Comment</td></tr>";

    foreach ($rows as $s) {
        $name = "{$s['LastName']}, {$s['FirstName']}" . ($s['EnglishName'] ? " ({$s['EnglishName']})" : "");
        $body .= "<tr><td>{$name}</td><td>{$s['Counselor']}</td><td>{$s['HAdvisor']}/{$s['HAdvisor2']}</td><td align='center'>Needs improvement</td><td>{$s['RRComment']}</td></tr>";
    }

    $body .= "</table><br>This report is automatically generated by Curfew/Bedtime report system.";
    sendReportEmail(['email' => 'boarding@bodwell.edu', 'name' => 'Boarding'], $adminEmails, $subject, $body);
}
?>
