<?php
require_once __DIR__.'/sendEmailClass.php';

$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$pdo = new PDO($dsn);

$thedate = date('Y-m-d');

// Get current semester
$stmt = $pdo->query("SELECT * FROM tblBHSSemester WHERE CurrentSemester = 'Y'");
$semester = $stmt->fetch(PDO::FETCH_ASSOC);

// Query student study hall data
$query = "
    SELECT s.StudentID, s.FirstName, s.LastName, s.EnglishName, s.Counselor, s.SchoolEmail,
           h.HAdvisor, h.HAdvisor2, h.Tutor,
           d.RComment, d.HAComment, d.RStudy, d.RMeet,
           st.Email3
    FROM tblBHSStudent s
    JOIN tblBHSDormDailyLog d ON s.StudentID = d.StudentID
    JOIN tblBHSHomestay h ON s.StudentID = h.StudentID
    JOIN tblStaff st ON h.HAdvisor = st.FirstName + ' ' + st.LastName
    WHERE d.RDate = ? AND d.StudyGroup = 'S'
      AND (d.RStudy = 1 OR d.RMeet = 1 OR d.RComment <> '')
      AND (d.SBlock IS NULL OR d.SBlock <> '6:00')
      AND st.SchoolID IN ('BHS','BSS') AND st.Email3 <> '' AND st.CurrentStaff = 'Y'
";
$stmt = $pdo->prepare($query);
$stmt->execute([$thedate]);
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

$advisorGroups = [];

foreach ($rows as $row) {
    $advisor = $row['HAdvisor'];
    if (!isset($advisorGroups[$advisor])) {
        $advisorGroups[$advisor] = [
            'rows' => []
        ];
    }
    $advisorGroups[$advisor]['rows'][] = $row;
}

foreach ($advisorGroups as $advisor => $data) {
    $html = "Here is the STUDY HALL Report on " . date('F d, Y', strtotime($thedate)) . "<br><br>";
    $html .= "Youth advisor: {$advisor}/{$data['rows'][0]['HAdvisor2']}<br><br>";
    $html .= "<table border='1' cellspacing='0' cellpadding='3' style='font-size:8pt;font-family:Verdana' bordercolor='#000000'>
        <tr><td>Student</td><td>Counselor</td><td>Tutor</td><td>PRESENT/ABSENT</td><td>## OF ABSENCES</td><td>TUTOR ASSESSMENT</td><td width='250'>Tutor comment</td><td width='250'>Advisor comment</td></tr>";

    foreach ($data['rows'] as $r) {
        if ($r['RStudy'] == 1) {
            $status = 'Unexcused Absent';
        } elseif ($r['RStudy'] == 5) {
            $status = 'Present';
        } elseif ($r['RStudy'] == 0) {
            $status = 'Excused Absent';
        } elseif ($r['RStudy'] == 2) {
            $status = 'Late 5 mins';
        } else {
            $status = '';
        }

        $absenceCount = '';
        if ($r['RStudy'] == 1) {
            $stmt2 = $pdo->prepare("SELECT COUNT(*) FROM tblBHSDormDailyLog WHERE StudentID = ? AND StudyGroup = 'S' AND RStudy = 1 AND RDate BETWEEN ? AND ? AND (SBlock IS NULL OR SBlock <> '6:00')");
            $stmt2->execute([$r['StudentID'], $semester['StartDate'], $semester['EndDate']]);
            $count = (int)$stmt2->fetchColumn();
            if ($count == 1) {
                $suffix = '1st';
            } elseif ($count == 2) {
                $suffix = '2nd';
            } elseif ($count == 3) {
                $suffix = '3rd';
            } else {
                $suffix = $count . 'th';
            }
            $absenceCount = $suffix;
        }

        if ($r['RMeet'] == 0) {
            $assessment = 'N/A';
        } elseif ($r['RMeet'] == 1) {
            $assessment = 'Needs improvement';
        } elseif ($r['RMeet'] == 5) {
            $assessment = 'Meets expectations';
        } else {
            $assessment = '';
        }

        $html .= "<tr><td>{$r['LastName']}, {$r['FirstName']}" . ($r['EnglishName'] ? " ({$r['EnglishName']})" : '') . "</td><td>{$r['Counselor']}</td><td>{$r['Tutor']}</td><td align='center'>{$status}</td><td align='center'>{$absenceCount}</td><td>{$assessment}</td><td>{$r['RComment']}</td><td>{$r['HAComment']}</td></tr>";
    }

    $html .= "</table><br>This report is automatically generated by STUDY HALL report system.";

    sendEmail(
        ['email' => 'no-reply@bodwell.edu', 'name' => 'Bodwell Study Hall Report'],
        [['email' => $data['rows'][0]['Email3'], 'name' => $advisor]],
        [],
        "STUDY HALL Report on $thedate",
        $html
    );
}
