<?php
require_once __DIR__.'/sendEmailClass.php';

$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$pdo = new PDO($dsn);

$weekday = date('N'); // 1 (Mon) to 5 (Fri)
if ($weekday >= 1 && $weekday <= 5) {
    $sql = "
    SELECT   s.StudentID, s.FirstName, s.LastName, s.EnglishName, s.Counselor,
             h.Hadvisor, h.Hadvisor2,
             SUM(a.Excuse) AS Excuse,
             SUM(a.AbsencePeriod) - SUM(a.Excuse) AS Unexcuse,
             SUM(a.AbsencePeriod) AS Absence
    FROM     tblBHSStudentSubject ss
    JOIN     tblBHSStudent s ON ss.StudNum = s.StudentID
    JOIN     tblBHSSubject subj ON ss.SubjectID = subj.SubjectID
    JOIN     tblBHSSemester sem ON subj.SemesterID = sem.SemesterID
    JOIN     tblBHSAttendance a ON ss.StudSubjID = a.StudSubjID
    JOIN     tblBHSHomestay h ON s.StudentID = h.StudentID
    WHERE    (a.Excusetxt IS NULL OR a.Excusetxt NOT IN ('S', 'F', 'A'))
             AND sem.CurrentSemester = 'Y'
             AND s.EA30 IS NULL
    GROUP BY s.StudentID, s.Counselor, s.FirstName, s.LastName, s.EnglishName, h.Hadvisor, h.Hadvisor2
    HAVING   SUM(a.AbsencePeriod) > 30
    ORDER BY s.Counselor";

    $rows = $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);

    if (count($rows) > 0) {
        $table = "<table border='1' cellspacing='0' cellpadding='3' style='font-size:10pt;font-family: Arial, Helvetica, sans-serif;'>
<tr><th>Student ID</th><th>First Name</th><th>Last Name</th><th>English Name</th><th>Counselor</th><th>Advisor 1</th><th>Advisor 2</th><th>Excused Absences<br>W/O S/F/A</th><th>Unexcused Absences</th><th>Total Absences</th></tr>";

        foreach ($rows as $r) {
            $table .= "<tr><td>{$r['StudentID']}</td><td>{$r['FirstName']}</td><td>{$r['LastName']}</td><td>{$r['EnglishName']}</td>
            <td>{$r['Counselor']}</td><td>{$r['Hadvisor']}</td><td>{$r['Hadvisor2']}</td>
            <td>{$r['Excuse']}</td><td>{$r['Unexcuse']}</td><td>{$r['Absence']}</td></tr>";

            $update = $pdo->prepare("UPDATE tblBHSStudent SET EA30 = 'Y' WHERE StudentID = ?");
            $update->execute([$r['StudentID']]);
        }

        $table .= "</table><br><br>This message is automatically generated by Bodwell database system.";

        $email1054 = $pdo->query("SELECT Email3 FROM tblStaff WHERE GroupTeam LIKE '%1054%' AND CurrentStaff = 'Y'")
                          ->fetchAll(PDO::FETCH_COLUMN);

        $recipients = array_map(function($email) {
            return ['email' => $email];
        }, $email1054);

        sendEmail(
            ['email' => 'no-reply@bodwell.edu', 'name' => 'Attendance Report'],
            $recipients,
            [],
            'Excessive Absences 30+ without S/F/A (automated email)',
            $table
        );

        $stmt = $pdo->prepare("INSERT INTO tblsendemail (sendto, sendfrom, sendsubject, sendattach, sendmessage, senddate, sentdate, schoolid, sendbcc) VALUES (?, ?, ?, ?, ?, GETDATE(),GETDATE(), ?, ?)");
        $stmt->execute([
            implode(';', $email1054),
            'no-reply@bodwell.edu',
            'Excessive Absences 30+ without S/F/A (automated email)',
            '',
            $table,
            'EAW',
            ''
        ]);
    }
}
