<?php
require_once __DIR__.'/sendEmailClass.php';

$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$pdo = new PDO($dsn);

// Fetch data
$sql = "
SELECT   s.StudentID, s.FirstName, s.LastName, s.EnglishName, s.Counselor,
         h.Hadvisor, h.Hadvisor2,
         SUM(a.Excuse) AS Excuse,
         SUM(a.AbsencePeriod) - SUM(a.Excuse) AS Unexcuse,
         SUM(a.AbsencePeriod) AS Absence
FROM     tblBHSStudentSubject ss
JOIN     tblBHSStudent s ON ss.StudNum = s.StudentID
JOIN     tblBHSSubject subj ON ss.SubjectID = subj.SubjectID
JOIN     tblBHSSemester sem ON subj.SemesterID = sem.SemesterID
JOIN     tblBHSAttendance a ON ss.StudSubjID = a.StudSubjID
JOIN     tblBHSHomestay h ON s.StudentID = h.StudentID
WHERE    sem.CurrentSemester = 'Y'
GROUP BY s.StudentID, s.Counselor, s.FirstName, s.LastName, s.EnglishName, h.Hadvisor, h.Hadvisor2
HAVING   SUM(a.AbsencePeriod) > 30
ORDER BY s.Counselor";

$rows = $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);

if (count($rows) > 0) {
    $table = "<table border='1' cellspacing='0' cellpadding='3' style='font-size:10pt;font-family: Arial, Helvetica, sans-serif;'>
<tr><th>Student ID</th><th>First Name</th><th>Last Name</th><th>English Name</th><th>Counselor</th><th>Advisor 1</th><th>Advisor 2</th><th>Excused Absences</th><th>Unexcused Absences</th><th>Total Absences</th></tr>";

    foreach ($rows as $r) {
        $table .= "<tr><td>{$r['StudentID']}</td><td>{$r['FirstName']}</td><td>{$r['LastName']}</td><td>{$r['EnglishName']}</td>
        <td>{$r['Counselor']}</td><td>{$r['Hadvisor']}</td><td>{$r['Hadvisor2']}</td>
        <td>{$r['Excuse']}</td><td>{$r['Unexcuse']}</td><td>{$r['Absence']}</td></tr>";
    }

    $table .= "</table><br><br>This message is automatically generated by Bodwell database system.";

    $email1048 = $pdo->query("SELECT Email3 FROM tblStaff WHERE GroupTeam LIKE '%1048%' AND CurrentStaff = 'Y' ORDER BY FirstName, LastName")
                     ->fetchAll(PDO::FETCH_COLUMN);

    $recipients = array_map(function($email) {
        return ['email' => $email];
    }, $email1048);

    sendEmail(
        ['email' => 'no-reply@bodwell.edu', 'name' => 'Attendance Report'],
        $recipients,
        [],
        'Excessive Absences 30+ (automated email)',
        $table
    );

    // Log to tblsendemail
    $stmt = $pdo->prepare("INSERT INTO tblsendemail (sendto, sendfrom, sendsubject, sendattach, sendmessage, senddate, sentdate, schoolid, sendbcc) VALUES (?, ?, ?, ?, ?, GETDATE(), GETDATE(), ?, ?)");
    $stmt->execute([
        implode(';', $email1048),
        'no-reply@bodwell.edu',
        'Excessive Absences 30+ (automated email)',
        '',
        $table,
        'EAS',
        ''
    ]);
}
