<?php
require_once __DIR__.'/sendEmailClass.php';

$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$pdo = new PDO($dsn);

$today = date('Y-m-d');
$dayOfWeek = date('w'); // Sunday = 0, Monday = 1, ..., Saturday = 6

// Skip weekends
if ($dayOfWeek >= 1 && $dayOfWeek <= 4) {
    // Check if today is a holiday
    $holidayDate = trim(file_get_contents('e:/admin.bodwell.edu/bhs/schedule/holiday.txt'));
    if ($holidayDate !== $today) {

        // Get current semester
        $semester = $pdo->query("SELECT TOP 1 SemesterID, StartDate, EndDate FROM tblBHSSemester WHERE CurrentSemester = 'Y'")->fetch(PDO::FETCH_ASSOC);
        if ($semester && $today >= $semester['StartDate'] && $today <= date('Y-m-d', strtotime($semester['EndDate'] . ' +1 day'))) {

            // Get English Tutorial subjects today
            $weekday = $dayOfWeek; // match with sday (Mon=1...Sun=7)
            $sql = "
                SELECT s.SubjectName, s.SubjectID, t.FirstName, t.LastName, t.Email3
                FROM tblBHSSUBJECT s
                JOIN tblStaff t ON s.TeacherID = t.StaffID
                WHERE s.SemesterID = ?
                  AND s.SubjectName LIKE '%English Tutorial%'
                  AND s.SDay LIKE ?
                  AND s.Type <> 'C'
                ORDER BY s.SubjectName
            ";
            $stmt = $pdo->prepare($sql);
            $stmt->execute([$semester['SemesterID'], "%{$weekday}%"]);
            $subjects = $stmt->fetchAll(PDO::FETCH_ASSOC);

            foreach ($subjects as $row) {
                $checkSql = "SELECT RDate FROM tblBHSAttendanceRpt WHERE SubjectID = ? AND SDate = ?";
                $stmtCheck = $pdo->prepare($checkSql);
                $stmtCheck->execute([$row['SubjectID'], $today]);

                if ($stmtCheck->rowCount() == 0) {
                    $subject = $row['SubjectName'];
                    $firstname = $row['FirstName'];

                    $html = "Dear {$firstname},<br><br>
                        According to our records, we did not receive an attendance report for {$subject} today.
                        Please submit the attendance report accordingly.<br><br>
                        <br>This message is automatically generated by Bodwell database system.";

                    sendEmail(
                        ['email' => 'deborah.moore@bodwell.edu', 'name' => 'Deborah Moore'],
                        [
                            ['email' => $row['Email3'], 'name' => $row['FirstName']],
                            ['email' => 'deborah.moore@bodwell.edu', 'name' => 'Deborah Moore']
                        ],
                        [['email' => 'keithlee@bodwell.edu', 'name' => 'Keith Lee']],
                        "Attendance reminder on {$today}",
                        $html
                    );
                }
            }
        }
    }
}
