<?php
require_once __DIR__.'/sendEmailClass.php';


$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$pdo = new PDO($dsn);
$dateToday = date('Y-m-d');


// Get Email Lists
function getEmailList($pdo, $groupCode) {
$stmt = $pdo->prepare("SELECT Email3 FROM tblStaff WHERE GroupTeam LIKE ? AND currentstaff = 'Y'");
$stmt->execute(['%' . $groupCode . '%']);
$emails = [];
while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
$emails[] = $row['Email3'];
}
return implode(';', $emails);
}

function parseRecipientsFromString($list, $defaultName = '') {
    if (!is_string($list) || $list === '') return array();
    // split by ; or , and trim
    $parts = preg_split('/[;,]+/', $list);
    $uniq  = array(); // dedupe by lowercase email
    $out   = array();

    foreach ($parts as $p) {
        $email = trim($p);
        if ($email === '') continue;
        // (optional) validate email
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) continue;
        $key = strtolower($email);
        if (isset($uniq[$key])) continue; // skip duplicates
        $uniq[$key] = true;
        $out[] = array('email' => $email, 'name' => $defaultName);
    }
    return $out;
}


$email1034 = getEmailList($pdo, '1034');
$email1053 = getEmailList($pdo, '1053');

$to1034 = parseRecipientsFromString($email1034);
$to1053 = parseRecipientsFromString($email1053);





// ADR and RO
$sql = "SELECT s.studentid, s.lastname, s.firstname, s.englishname, s.sex, s.origin, s.counselor, CONVERT(CHAR(10), s.dob, 126) dob,
c.emailpersonal AS email, co.cname, 'Parent/Guardian 1' as contact
FROM tblbhsstudent s
JOIN tblbhsstudentcontact c ON s.studentid = c.studentid
JOIN tblcountry co ON s.origin = co.cid
WHERE s.currentstudent = 'Y' AND c.evinternal = 0 AND c.emailpersonal <> '' AND c.contacttab = 'PG1'
ORDER BY s.counselor, s.lastname, s.firstname, s.englishname";
$students = $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);


if (count($students) > 0) {
$body = "Hi,<br><br>The following current student's Parent/Guardian 1 email address has NOT been verified.<br><br>";
$body .= "<table border='1' cellspacing='0' cellpadding='0' style='font-size:10pt;'>";
$body .= "<tr align='center' height='30'><td>Student ID</td><td>Student Name</td><td>Sex</td><td>DOB</td><td>Origin</td><td>Counsellor</td><td>Contact</td><td>Email</td></tr>";
foreach ($students as $s) {
$fullname = $s['lastname'] . ', ' . $s['firstname'] . ($s['englishname'] != '' ? ' (' . $s['englishname'] . ')' : '');
$body .= "<tr><td>{$s['studentid']}</td><td>$fullname</td><td align='center'>{$s['sex']}</td><td>{$s['dob']}</td><td>" . substr($s['cname'], 0, 20) . "</td><td>{$s['counselor']}</td><td>{$s['contact']}</td><td>{$s['email']}</td></tr>";
}
$body .= "</table><br>This message is automatically generated by Bodwell database system.";


echo sendEmail(
['email' => 'no-reply@bodwell.edu', 'name' => 'Bodwell System'],
$to1034,
// [['email' => 'chanho.lee@bodwell.edu', 'name' => 'Group 1034']],
[],
"Email address NOT verified Notice",
$body
);
}


// University in-progress
$sql = "SELECT a.StudentID, a.Appliedtos, cu.ColUni, s.FirstName, s.LastName, s.EnglishName, s.Counselor
FROM tblBHSStudentApplied a
JOIN tblBHSCollegeUniversity cu ON a.Appliedto = cu.cuid
JOIN tblBHSStudent s ON a.StudentID = s.StudentID
WHERE a.Appliedtos = 'in progress'";
$rows = $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);


if (count($rows) > 0) {
$body = "Hi,<br><br>The following student's University/College is in progress.<br><br>";
$body .= "<table border='1' cellspacing='0' cellpadding='0' style='font-size:10pt;'>";
$body .= "<tr align='center' height='30'><td>Student ID</td><td>Student Name</td><td>Counsellor</td><td>University/College</td></tr>";
foreach ($rows as $r) {
$name = $r['LastName'] . ', ' . $r['FirstName'] . ($r['EnglishName'] != '' ? ' (' . $r['EnglishName'] . ')' : '');
$body .= "<tr><td>{$r['StudentID']}</td><td>$name</td><td>{$r['Counselor']}</td><td>{$r['ColUni']}</td></tr>";
}
$body .= "</table><br>This message is automatically generated by Bodwell database system.";


echo sendEmail(
['email' => 'no-reply@bodwell.edu', 'name' => 'Bodwell System'],
$to1053,
// [['email' => 'chanho.lee@bodwell.edu', 'name' => 'Group 1034']],
[],
"University/College - in progress",
$body
);
}


// Outstanding Deadline Warning
$deadlineDate = date('Y-m-d', strtotime('+14 days'));
$sql = "SELECT o.StudentID, s.FirstName, s.LastName, s.EnglishName, o.FeeType, CONVERT(CHAR(10), o.StartDate, 126) StartDate, CONVERT(CHAR(10), o.ExpireDate, 126) ExpireDate, o.Amount, CONVERT(CHAR(10), o.Deadline, 126) Deadline, o.Remarks
FROM tblBHSOutstanding o
JOIN tblBHSStudent s ON o.StudentID = s.StudentID
WHERE o.Deadline < '$deadlineDate'
ORDER BY o.Deadline, s.LastName, s.FirstName";
$outstanding = $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);


if (count($outstanding) > 0) {
$body = "<table border='1' cellspacing='0' cellpadding='0' style='font-size:10pt;'>";
$body .= "<tr><th>Student ID</th><th>Student Name</th><th>Fee Type</th><th>Start Date</th><th>Expire Date</th><th>Amount</th><th>Deadline</th><th style='width:300px;'>Remarks</th></tr>";
foreach ($outstanding as $o) {
$name = $o['LastName'] . ', ' . $o['FirstName'] . ($o['EnglishName'] != '' ? ' (' . $o['EnglishName'] . ')' : '');
$amount = number_format($o['Amount'], 2);
$body .= "<tr><td>{$o['StudentID']}</td><td>$name</td><td>{$o['FeeType']}</td><td>{$o['StartDate']}</td><td>{$o['ExpireDate']}</td><td align='right'>$amount</td><td>{$o['Deadline']}</td><td style='width:300px;'>{$o['Remarks']}</td></tr>";
}
$body .= "</table><br>This message is automatically generated by Bodwell database system.";


echo sendEmail(
['email' => 'no-reply@bodwell.edu', 'name' => 'Bodwell System'],
$to1034,
// [['email' => 'chanho.lee@bodwell.edu', 'name' => 'Group 1034']],
[],
"Outstanding fee - Deadline",
$body
);
}
