<?php
date_default_timezone_set("America/Vancouver");
require_once __DIR__ . '/sendEmailClass.php';

$hour = intval(date("G")); // 24-hour format
$dayOfWeek = intval(date("N")); // 1=Mon ... 7=Sun

if (!(($dayOfWeek == 6 || $dayOfWeek == 7) && $hour == 8) && $hour != 15) {
    exit; // only run 3:50pm weekdays, or 8:50am weekends
}

$dsn = "odbc:Driver={SQL Server};Server=10.100.4.6;Database=Bodwell;Uid=web;Pwd=AJgw!cG4nw;";
$pdo = new PDO($dsn);

// 1. Get RemoteEmail list (GroupTeam 1025)
$getRemoteEmail = $pdo->query("
    SELECT Email3 FROM tblStaff
    WHERE GroupTeam LIKE '%1025%'
      AND currentstaff = 'Y'
      AND Email3 <> ''
");
$remoteEmails = $getRemoteEmail->fetchAll(PDO::FETCH_COLUMN, 0);
$emaillist = implode(";", $remoteEmails);

// 2. Get isolating/excused student data
$sql = "
SELECT
  s.StudentID,
  s.FirstName,
  s.LastName,
  s.EnglishName,
  s.Counselor,
  h.RoomNo,
  h.HAdvisor,
  h.HAdvisor2,
  CASE h.Quarantine
    WHEN 'Y' THEN 'Isolating for HS'
    WHEN 'U' THEN 'Isolating for Hotel'
    WHEN 'H' THEN 'Isolating for Homestay'
    WHEN 'D' THEN 'Isolating for Day'
    WHEN 'M' THEN 'Excused'
  END AS Quarantine
FROM tblBHSStudent s
JOIN tblBHSHomestay h ON h.StudentID = s.StudentID
WHERE h.Quarantine IN ('Y','U','H','D','M')
ORDER BY s.LastName, s.FirstName";

$stmt = $pdo->query($sql);
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

$today = date("Y-m-d");
$subject = "Isolating or Excused Students on $today";

// 3. Compose email message
$message = "";
if (count($rows) === 0) {
    $message .= "There is no \"isolating or excused students\" today.<br>";
} else {
    $message .= "Below are the \"isolating or excused students\".<br><br>";
    $message .= "<table border='1' cellspacing='0' cellpadding='0' style='font-size:10pt;font-family:Verdana'>";
    $message .= "<tr bgcolor='#C0C0C0'><td>&nbsp;</td><td>Student Name</td><td>Room Number</td><td>Advisors</td><td>Counselor</td></tr>";

    foreach ($rows as $row) {
        $studentName = $row['LastName'] . ', ' . $row['FirstName'];
        if (!empty($row['EnglishName'])) {
            $studentName .= " (" . $row['EnglishName'] . ")";
        }

        $advisorCombo = $row['HAdvisor'];
        if (!empty($row['HAdvisor2'])) {
            $advisorCombo .= '/' . $row['HAdvisor2'];
        }

        $message .= "<tr>";
        $message .= "<td>{$row['Quarantine']}</td>";
        $message .= "<td>{$studentName}</td>";
        $message .= "<td>{$row['RoomNo']}</td>";
        $message .= "<td>{$advisorCombo}</td>";
        $message .= "<td>{$row['Counselor']}</td>";
        $message .= "</tr>";
    }

    $message .= "</table>";
}
$message .= "<br>This message is automatically generated by Bodwell database system.";

// 4. Send email
sendEmail([
    'from' => 'no-reply@bodwell.edu',
    'to' => $emaillist,
    'subject' => $subject,
    'body' => $message
]);

// 5. Log send
$log = $pdo->prepare("
    INSERT INTO tblSendEmail (sendto, sendfrom, sendsubject, sendattach, sendmessage, senddate, schoolid)
    VALUES (?, ?, ?, ?, ?, ?, ?)
");
$log->execute([
    $emaillist,
    'no-reply@bodwell.edu',
    $subject,
    '',
    $message,
    date("Y-m-d H:i:s"),
    'RSR'
]);
?>
